nelmio_api_doc:
    documentation:
        info:
            title: Cleaner Service
            description: Justmop assignment
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!_error|api/doc*) # Accepts routes under /api eapixcept /api/doc
